// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from github.com/ethp2p/xray/api. DO NOT EDIT.
// Run `tygo generate` (or `bun run gen`) after editing api/api.go.

//////////
// source: api.go
/*
Package api defines the JSON contract between the xray backend and any
consumer of its REST/WebSocket surface (today: the Solid.js dashboard).

These types are the source of truth: tygo regenerates the matching
TypeScript declarations into dashboard/src/api.gen.ts as part of the
dashboard build, so drift between Go and TS is caught at compile time.
*/

/**
 * BleedDistEntry counts bytes attributed to a particular bleed distance bucket
 * ("1", "2", "3", "4+") for a slot or per-bucket breakdown row.
 */
export interface BleedDistEntry {
  bytes_in: number /* uint64 */;
  bytes_out: number /* uint64 */;
}
/**
 * SlotMeta carries per-slot metadata extracted from beacon block / attestation
 * payloads. All fields are optional because the slot may not have observed a
 * full block yet.
 */
export interface SlotMeta {
  proposer_index?: number /* uint64 */;
  attestation_count?: number /* int */;
  blob_commitments?: number /* int */;
  tx_count?: number /* int */;
  bleed_bytes_in?: number /* uint64 */;
  bleed_bytes_out?: number /* uint64 */;
}
/**
 * SlotSummary is the headline view of a slot: totals, timing, and finalization.
 */
export interface SlotSummary {
  slot: number /* uint64 */;
  epoch: number /* uint64 */;
  slot_start_ns: number /* int64 */;
  slot_end_ns: number /* int64 */;
  bytes_in: number /* uint64 */;
  bytes_out: number /* uint64 */;
  finalized: boolean;
  last_updated_ns: number /* int64 */;
  meta: SlotMeta;
}
/**
 * SlotBucketPoint is one 100ms bucket of traffic within a slot.
 */
export interface SlotBucketPoint {
  offset_ms: number /* int64 */;
  bytes_in: number /* uint64 */;
  bytes_out: number /* uint64 */;
  breakdown?: BucketBreakdown[];
}
/**
 * BucketBreakdown attributes bytes within a single time bucket to a specific
 * (protocol, topic, message_kind) tuple.
 */
export interface BucketBreakdown {
  protocol: string;
  topic: string;
  message_kind: string;
  bytes_in: number /* uint64 */;
  bytes_out: number /* uint64 */;
  msg_count: number /* uint64 */;
  bleed_bytes_in: number /* uint64 */;
  bleed_bytes_out: number /* uint64 */;
  bleed_by_distance?: { [key: string]: BleedDistEntry};
}
/**
 * SlotBreakdown is the slot-level aggregate analogue of BucketBreakdown.
 */
export interface SlotBreakdown {
  protocol: string;
  topic: string;
  message_kind: string;
  bytes_in: number /* uint64 */;
  bytes_out: number /* uint64 */;
  msg_count: number /* uint64 */;
  bleed_bytes_in: number /* uint64 */;
  bleed_bytes_out: number /* uint64 */;
  bleed_by_distance?: { [key: string]: BleedDistEntry};
}
/**
 * SlotDetail is the full per-slot payload returned by GET /api/slots/{slot}.
 */
export interface SlotDetail {
  summary: SlotSummary;
  buckets: SlotBucketPoint[];
  breakdown: SlotBreakdown[];
}
/**
 * ConnState describes a single libp2p connection a peer holds with the source.
 */
export interface ConnState {
  remote_addr: string;
  local_addr?: string;
  direction: string;
  transport?: string;
  security?: string;
  muxer?: string;
  opened_at_ns: number /* int64 */;
}
/**
 * PeerSummary is one row in the response to GET /api/peers.
 */
export interface PeerSummary {
  peer_id: string;
  connections: ConnState[];
  first_seen_ns: number /* int64 */;
  last_seen_ns: number /* int64 */;
}
/**
 * WsMessage is the union of WebSocket payloads pushed by the server.
 * The Type field discriminates: "snapshot" carries Current and PeerCount;
 * "slot_update" carries a single Slot; "slot_batch" carries Slots and Current.
 */
export interface WsMessage {
  type: string;
  source_id?: string;
  slot?: SlotSummary;
  slots?: SlotSummary[];
  current_slot?: number /* uint64 */;
  peer_count?: number /* int */;
}
