// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/wiretap.proto

package wiretappbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/ethp2p/wiretap/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WiretapServiceName is the fully-qualified name of the WiretapService service.
	WiretapServiceName = "wiretap.v1.WiretapService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WiretapServiceStreamEventsProcedure is the fully-qualified name of the WiretapService's
	// StreamEvents RPC.
	WiretapServiceStreamEventsProcedure = "/wiretap.v1.WiretapService/StreamEvents"
)

// WiretapServiceClient is a client for the wiretap.v1.WiretapService service.
type WiretapServiceClient interface {
	// Client sends handshake, server streams events
	StreamEvents(context.Context, *connect.Request[proto.Handshake]) (*connect.ServerStreamForClient[proto.ServerMessage], error)
}

// NewWiretapServiceClient constructs a client for the wiretap.v1.WiretapService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWiretapServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WiretapServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	wiretapServiceMethods := proto.File_proto_wiretap_proto.Services().ByName("WiretapService").Methods()
	return &wiretapServiceClient{
		streamEvents: connect.NewClient[proto.Handshake, proto.ServerMessage](
			httpClient,
			baseURL+WiretapServiceStreamEventsProcedure,
			connect.WithSchema(wiretapServiceMethods.ByName("StreamEvents")),
			connect.WithClientOptions(opts...),
		),
	}
}

// wiretapServiceClient implements WiretapServiceClient.
type wiretapServiceClient struct {
	streamEvents *connect.Client[proto.Handshake, proto.ServerMessage]
}

// StreamEvents calls wiretap.v1.WiretapService.StreamEvents.
func (c *wiretapServiceClient) StreamEvents(ctx context.Context, req *connect.Request[proto.Handshake]) (*connect.ServerStreamForClient[proto.ServerMessage], error) {
	return c.streamEvents.CallServerStream(ctx, req)
}

// WiretapServiceHandler is an implementation of the wiretap.v1.WiretapService service.
type WiretapServiceHandler interface {
	// Client sends handshake, server streams events
	StreamEvents(context.Context, *connect.Request[proto.Handshake], *connect.ServerStream[proto.ServerMessage]) error
}

// NewWiretapServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWiretapServiceHandler(svc WiretapServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	wiretapServiceMethods := proto.File_proto_wiretap_proto.Services().ByName("WiretapService").Methods()
	wiretapServiceStreamEventsHandler := connect.NewServerStreamHandler(
		WiretapServiceStreamEventsProcedure,
		svc.StreamEvents,
		connect.WithSchema(wiretapServiceMethods.ByName("StreamEvents")),
		connect.WithHandlerOptions(opts...),
	)
	return "/wiretap.v1.WiretapService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WiretapServiceStreamEventsProcedure:
			wiretapServiceStreamEventsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWiretapServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWiretapServiceHandler struct{}

func (UnimplementedWiretapServiceHandler) StreamEvents(context.Context, *connect.Request[proto.Handshake], *connect.ServerStream[proto.ServerMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("wiretap.v1.WiretapService.StreamEvents is not implemented"))
}
