// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pb/wiretap.proto

package instrumentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_DIRECTION_UNKNOWN Direction = 0
	Direction_DIRECTION_IN      Direction = 1
	Direction_DIRECTION_OUT     Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNKNOWN",
		1: "DIRECTION_IN",
		2: "DIRECTION_OUT",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNKNOWN": 0,
		"DIRECTION_IN":      1,
		"DIRECTION_OUT":     2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_wiretap_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_pb_wiretap_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{0}
}

// Top-level event wrapper
type TraceEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Seq         uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`                                    // monotonic sequence number
	TimestampNs int64                  `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"` // unix nanos
	// Types that are valid to be assigned to Event:
	//
	//	*TraceEvent_Snapshot
	//	*TraceEvent_StringDef
	//	*TraceEvent_ConnOpened
	//	*TraceEvent_ConnClosed
	//	*TraceEvent_StreamOpened
	//	*TraceEvent_StreamClosed
	//	*TraceEvent_Traffic
	Event         isTraceEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceEvent) Reset() {
	*x = TraceEvent{}
	mi := &file_pb_wiretap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceEvent) ProtoMessage() {}

func (x *TraceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceEvent.ProtoReflect.Descriptor instead.
func (*TraceEvent) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{0}
}

func (x *TraceEvent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TraceEvent) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *TraceEvent) GetEvent() isTraceEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TraceEvent) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Event.(*TraceEvent_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *TraceEvent) GetStringDef() *StringDef {
	if x != nil {
		if x, ok := x.Event.(*TraceEvent_StringDef); ok {
			return x.StringDef
		}
	}
	return nil
}

func (x *TraceEvent) GetConnOpened() *ConnOpened {
	if x != nil {
		if x, ok := x.Event.(*TraceEvent_ConnOpened); ok {
			return x.ConnOpened
		}
	}
	return nil
}

func (x *TraceEvent) GetConnClosed() *ConnClosed {
	if x != nil {
		if x, ok := x.Event.(*TraceEvent_ConnClosed); ok {
			return x.ConnClosed
		}
	}
	return nil
}

func (x *TraceEvent) GetStreamOpened() *StreamOpened {
	if x != nil {
		if x, ok := x.Event.(*TraceEvent_StreamOpened); ok {
			return x.StreamOpened
		}
	}
	return nil
}

func (x *TraceEvent) GetStreamClosed() *StreamClosed {
	if x != nil {
		if x, ok := x.Event.(*TraceEvent_StreamClosed); ok {
			return x.StreamClosed
		}
	}
	return nil
}

func (x *TraceEvent) GetTraffic() *Traffic {
	if x != nil {
		if x, ok := x.Event.(*TraceEvent_Traffic); ok {
			return x.Traffic
		}
	}
	return nil
}

type isTraceEvent_Event interface {
	isTraceEvent_Event()
}

type TraceEvent_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,10,opt,name=snapshot,proto3,oneof"`
}

type TraceEvent_StringDef struct {
	StringDef *StringDef `protobuf:"bytes,11,opt,name=string_def,json=stringDef,proto3,oneof"`
}

type TraceEvent_ConnOpened struct {
	ConnOpened *ConnOpened `protobuf:"bytes,12,opt,name=conn_opened,json=connOpened,proto3,oneof"`
}

type TraceEvent_ConnClosed struct {
	ConnClosed *ConnClosed `protobuf:"bytes,13,opt,name=conn_closed,json=connClosed,proto3,oneof"`
}

type TraceEvent_StreamOpened struct {
	StreamOpened *StreamOpened `protobuf:"bytes,14,opt,name=stream_opened,json=streamOpened,proto3,oneof"`
}

type TraceEvent_StreamClosed struct {
	StreamClosed *StreamClosed `protobuf:"bytes,15,opt,name=stream_closed,json=streamClosed,proto3,oneof"`
}

type TraceEvent_Traffic struct {
	Traffic *Traffic `protobuf:"bytes,16,opt,name=traffic,proto3,oneof"`
}

func (*TraceEvent_Snapshot) isTraceEvent_Event() {}

func (*TraceEvent_StringDef) isTraceEvent_Event() {}

func (*TraceEvent_ConnOpened) isTraceEvent_Event() {}

func (*TraceEvent_ConnClosed) isTraceEvent_Event() {}

func (*TraceEvent_StreamOpened) isTraceEvent_Event() {}

func (*TraceEvent_StreamClosed) isTraceEvent_Event() {}

func (*TraceEvent_Traffic) isTraceEvent_Event() {}

// Full state snapshot for new consumers or file seeking
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       []string               `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"` // string intern table (index = id)
	Connections   []*ConnInfo            `protobuf:"bytes,2,rep,name=connections,proto3" json:"connections,omitempty"`
	Streams       []*StreamInfo          `protobuf:"bytes,3,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_pb_wiretap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{1}
}

func (x *Snapshot) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *Snapshot) GetConnections() []*ConnInfo {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *Snapshot) GetStreams() []*StreamInfo {
	if x != nil {
		return x.Streams
	}
	return nil
}

// New interned string (emitted inline when first encountered)
type StringDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringDef) Reset() {
	*x = StringDef{}
	mi := &file_pb_wiretap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringDef) ProtoMessage() {}

func (x *StringDef) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringDef.ProtoReflect.Descriptor instead.
func (*StringDef) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{2}
}

func (x *StringDef) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StringDef) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Connection metadata
type ConnInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint32                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	PeerId        []byte                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	RemoteAddr    string                 `protobuf:"bytes,3,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"` // multiaddr
	Direction     Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=wiretap.v1.Direction" json:"direction,omitempty"`
	Transport     string                 `protobuf:"bytes,5,opt,name=transport,proto3" json:"transport,omitempty"` // tcp, quic, etc.
	Muxer         string                 `protobuf:"bytes,6,opt,name=muxer,proto3" json:"muxer,omitempty"`         // yamux, mplex, etc.
	Security      string                 `protobuf:"bytes,7,opt,name=security,proto3" json:"security,omitempty"`   // tls, noise, etc.
	OpenedAtNs    int64                  `protobuf:"varint,8,opt,name=opened_at_ns,json=openedAtNs,proto3" json:"opened_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnInfo) Reset() {
	*x = ConnInfo{}
	mi := &file_pb_wiretap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnInfo) ProtoMessage() {}

func (x *ConnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnInfo.ProtoReflect.Descriptor instead.
func (*ConnInfo) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{3}
}

func (x *ConnInfo) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *ConnInfo) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *ConnInfo) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *ConnInfo) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNKNOWN
}

func (x *ConnInfo) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ConnInfo) GetMuxer() string {
	if x != nil {
		return x.Muxer
	}
	return ""
}

func (x *ConnInfo) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *ConnInfo) GetOpenedAtNs() int64 {
	if x != nil {
		return x.OpenedAtNs
	}
	return 0
}

type ConnOpened struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *ConnInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnOpened) Reset() {
	*x = ConnOpened{}
	mi := &file_pb_wiretap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnOpened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnOpened) ProtoMessage() {}

func (x *ConnOpened) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnOpened.ProtoReflect.Descriptor instead.
func (*ConnOpened) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{4}
}

func (x *ConnOpened) GetInfo() *ConnInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ConnClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint32                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	DurationNs    int64                  `protobuf:"varint,2,opt,name=duration_ns,json=durationNs,proto3" json:"duration_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnClosed) Reset() {
	*x = ConnClosed{}
	mi := &file_pb_wiretap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnClosed) ProtoMessage() {}

func (x *ConnClosed) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnClosed.ProtoReflect.Descriptor instead.
func (*ConnClosed) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{5}
}

func (x *ConnClosed) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *ConnClosed) GetDurationNs() int64 {
	if x != nil {
		return x.DurationNs
	}
	return 0
}

// Stream metadata
type StreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ConnId        uint32                 `protobuf:"varint,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	ProtocolId    uint32                 `protobuf:"varint,3,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"` // interned string id
	Direction     Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=wiretap.v1.Direction" json:"direction,omitempty"`
	OpenedAtNs    int64                  `protobuf:"varint,5,opt,name=opened_at_ns,json=openedAtNs,proto3" json:"opened_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_pb_wiretap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{6}
}

func (x *StreamInfo) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *StreamInfo) GetConnId() uint32 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *StreamInfo) GetProtocolId() uint32 {
	if x != nil {
		return x.ProtocolId
	}
	return 0
}

func (x *StreamInfo) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNKNOWN
}

func (x *StreamInfo) GetOpenedAtNs() int64 {
	if x != nil {
		return x.OpenedAtNs
	}
	return 0
}

type StreamOpened struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *StreamInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOpened) Reset() {
	*x = StreamOpened{}
	mi := &file_pb_wiretap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOpened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOpened) ProtoMessage() {}

func (x *StreamOpened) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOpened.ProtoReflect.Descriptor instead.
func (*StreamOpened) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{7}
}

func (x *StreamOpened) GetInfo() *StreamInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type StreamClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamClosed) Reset() {
	*x = StreamClosed{}
	mi := &file_pb_wiretap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamClosed) ProtoMessage() {}

func (x *StreamClosed) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamClosed.ProtoReflect.Descriptor instead.
func (*StreamClosed) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{8}
}

func (x *StreamClosed) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

// Per-message traffic event
type Traffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      uint32                 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Direction     Direction              `protobuf:"varint,2,opt,name=direction,proto3,enum=wiretap.v1.Direction" json:"direction,omitempty"`
	Bytes         uint32                 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Tags          []*Tag                 `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Traffic) Reset() {
	*x = Traffic{}
	mi := &file_pb_wiretap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Traffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Traffic) ProtoMessage() {}

func (x *Traffic) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Traffic.ProtoReflect.Descriptor instead.
func (*Traffic) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{9}
}

func (x *Traffic) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Traffic) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNKNOWN
}

func (x *Traffic) GetBytes() uint32 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Traffic) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Tag with interned strings
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameId        uint32                 `protobuf:"varint,1,opt,name=name_id,json=nameId,proto3" json:"name_id,omitempty"`
	ValueIds      []uint32               `protobuf:"varint,2,rep,packed,name=value_ids,json=valueIds,proto3" json:"value_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_pb_wiretap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{10}
}

func (x *Tag) GetNameId() uint32 {
	if x != nil {
		return x.NameId
	}
	return 0
}

func (x *Tag) GetValueIds() []uint32 {
	if x != nil {
		return x.ValueIds
	}
	return nil
}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeFromSeq uint64                 `protobuf:"varint,1,opt,name=resume_from_seq,json=resumeFromSeq,proto3" json:"resume_from_seq,omitempty"` // 0 = start fresh with snapshot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_pb_wiretap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{11}
}

func (x *Handshake) GetResumeFromSeq() uint64 {
	if x != nil {
		return x.ResumeFromSeq
	}
	return 0
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_Event
	//	*ServerMessage_Slow
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_pb_wiretap_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{12}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetEvent() *TraceEvent {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ServerMessage) GetSlow() *SlowWarning {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Slow); ok {
			return x.Slow
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_Event struct {
	Event *TraceEvent `protobuf:"bytes,1,opt,name=event,proto3,oneof"`
}

type ServerMessage_Slow struct {
	Slow *SlowWarning `protobuf:"bytes,2,opt,name=slow,proto3,oneof"`
}

func (*ServerMessage_Event) isServerMessage_Msg() {}

func (*ServerMessage_Slow) isServerMessage_Msg() {}

// Signals client is consuming too slowly
type SlowWarning struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BufferedEvents uint64                 `protobuf:"varint,1,opt,name=buffered_events,json=bufferedEvents,proto3" json:"buffered_events,omitempty"`
	DroppedEvents  uint64                 `protobuf:"varint,2,opt,name=dropped_events,json=droppedEvents,proto3" json:"dropped_events,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SlowWarning) Reset() {
	*x = SlowWarning{}
	mi := &file_pb_wiretap_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlowWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowWarning) ProtoMessage() {}

func (x *SlowWarning) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wiretap_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowWarning.ProtoReflect.Descriptor instead.
func (*SlowWarning) Descriptor() ([]byte, []int) {
	return file_pb_wiretap_proto_rawDescGZIP(), []int{13}
}

func (x *SlowWarning) GetBufferedEvents() uint64 {
	if x != nil {
		return x.BufferedEvents
	}
	return 0
}

func (x *SlowWarning) GetDroppedEvents() uint64 {
	if x != nil {
		return x.DroppedEvents
	}
	return 0
}

var File_pb_wiretap_proto protoreflect.FileDescriptor

const file_pb_wiretap_proto_rawDesc = "" +
	"\n" +
	"\x10pb/wiretap.proto\x12\n" +
	"wiretap.v1\"\xdf\x03\n" +
	"\n" +
	"TraceEvent\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x03R\vtimestampNs\x122\n" +
	"\bsnapshot\x18\n" +
	" \x01(\v2\x14.wiretap.v1.SnapshotH\x00R\bsnapshot\x126\n" +
	"\n" +
	"string_def\x18\v \x01(\v2\x15.wiretap.v1.StringDefH\x00R\tstringDef\x129\n" +
	"\vconn_opened\x18\f \x01(\v2\x16.wiretap.v1.ConnOpenedH\x00R\n" +
	"connOpened\x129\n" +
	"\vconn_closed\x18\r \x01(\v2\x16.wiretap.v1.ConnClosedH\x00R\n" +
	"connClosed\x12?\n" +
	"\rstream_opened\x18\x0e \x01(\v2\x18.wiretap.v1.StreamOpenedH\x00R\fstreamOpened\x12?\n" +
	"\rstream_closed\x18\x0f \x01(\v2\x18.wiretap.v1.StreamClosedH\x00R\fstreamClosed\x12/\n" +
	"\atraffic\x18\x10 \x01(\v2\x13.wiretap.v1.TrafficH\x00R\atrafficB\a\n" +
	"\x05event\"\x8e\x01\n" +
	"\bSnapshot\x12\x18\n" +
	"\astrings\x18\x01 \x03(\tR\astrings\x126\n" +
	"\vconnections\x18\x02 \x03(\v2\x14.wiretap.v1.ConnInfoR\vconnections\x120\n" +
	"\astreams\x18\x03 \x03(\v2\x16.wiretap.v1.StreamInfoR\astreams\"1\n" +
	"\tStringDef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x84\x02\n" +
	"\bConnInfo\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\rR\x06connId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\fR\x06peerId\x12\x1f\n" +
	"\vremote_addr\x18\x03 \x01(\tR\n" +
	"remoteAddr\x123\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x15.wiretap.v1.DirectionR\tdirection\x12\x1c\n" +
	"\ttransport\x18\x05 \x01(\tR\ttransport\x12\x14\n" +
	"\x05muxer\x18\x06 \x01(\tR\x05muxer\x12\x1a\n" +
	"\bsecurity\x18\a \x01(\tR\bsecurity\x12 \n" +
	"\fopened_at_ns\x18\b \x01(\x03R\n" +
	"openedAtNs\"6\n" +
	"\n" +
	"ConnOpened\x12(\n" +
	"\x04info\x18\x01 \x01(\v2\x14.wiretap.v1.ConnInfoR\x04info\"F\n" +
	"\n" +
	"ConnClosed\x12\x17\n" +
	"\aconn_id\x18\x01 \x01(\rR\x06connId\x12\x1f\n" +
	"\vduration_ns\x18\x02 \x01(\x03R\n" +
	"durationNs\"\xba\x01\n" +
	"\n" +
	"StreamInfo\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12\x17\n" +
	"\aconn_id\x18\x02 \x01(\rR\x06connId\x12\x1f\n" +
	"\vprotocol_id\x18\x03 \x01(\rR\n" +
	"protocolId\x123\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x15.wiretap.v1.DirectionR\tdirection\x12 \n" +
	"\fopened_at_ns\x18\x05 \x01(\x03R\n" +
	"openedAtNs\":\n" +
	"\fStreamOpened\x12*\n" +
	"\x04info\x18\x01 \x01(\v2\x16.wiretap.v1.StreamInfoR\x04info\"+\n" +
	"\fStreamClosed\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\"\x96\x01\n" +
	"\aTraffic\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x123\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x15.wiretap.v1.DirectionR\tdirection\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\rR\x05bytes\x12#\n" +
	"\x04tags\x18\x04 \x03(\v2\x0f.wiretap.v1.TagR\x04tags\";\n" +
	"\x03Tag\x12\x17\n" +
	"\aname_id\x18\x01 \x01(\rR\x06nameId\x12\x1b\n" +
	"\tvalue_ids\x18\x02 \x03(\rR\bvalueIds\"3\n" +
	"\tHandshake\x12&\n" +
	"\x0fresume_from_seq\x18\x01 \x01(\x04R\rresumeFromSeq\"u\n" +
	"\rServerMessage\x12.\n" +
	"\x05event\x18\x01 \x01(\v2\x16.wiretap.v1.TraceEventH\x00R\x05event\x12-\n" +
	"\x04slow\x18\x02 \x01(\v2\x17.wiretap.v1.SlowWarningH\x00R\x04slowB\x05\n" +
	"\x03msg\"]\n" +
	"\vSlowWarning\x12'\n" +
	"\x0fbuffered_events\x18\x01 \x01(\x04R\x0ebufferedEvents\x12%\n" +
	"\x0edropped_events\x18\x02 \x01(\x04R\rdroppedEvents*G\n" +
	"\tDirection\x12\x15\n" +
	"\x11DIRECTION_UNKNOWN\x10\x00\x12\x10\n" +
	"\fDIRECTION_IN\x10\x01\x12\x11\n" +
	"\rDIRECTION_OUT\x10\x022T\n" +
	"\x0eWiretapService\x12B\n" +
	"\fStreamEvents\x12\x15.wiretap.v1.Handshake\x1a\x19.wiretap.v1.ServerMessage0\x01B.Z,github.com/ethp2p/instrument/pb;instrumentpbb\x06proto3"

var (
	file_pb_wiretap_proto_rawDescOnce sync.Once
	file_pb_wiretap_proto_rawDescData []byte
)

func file_pb_wiretap_proto_rawDescGZIP() []byte {
	file_pb_wiretap_proto_rawDescOnce.Do(func() {
		file_pb_wiretap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_wiretap_proto_rawDesc), len(file_pb_wiretap_proto_rawDesc)))
	})
	return file_pb_wiretap_proto_rawDescData
}

var file_pb_wiretap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_wiretap_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pb_wiretap_proto_goTypes = []any{
	(Direction)(0),        // 0: wiretap.v1.Direction
	(*TraceEvent)(nil),    // 1: wiretap.v1.TraceEvent
	(*Snapshot)(nil),      // 2: wiretap.v1.Snapshot
	(*StringDef)(nil),     // 3: wiretap.v1.StringDef
	(*ConnInfo)(nil),      // 4: wiretap.v1.ConnInfo
	(*ConnOpened)(nil),    // 5: wiretap.v1.ConnOpened
	(*ConnClosed)(nil),    // 6: wiretap.v1.ConnClosed
	(*StreamInfo)(nil),    // 7: wiretap.v1.StreamInfo
	(*StreamOpened)(nil),  // 8: wiretap.v1.StreamOpened
	(*StreamClosed)(nil),  // 9: wiretap.v1.StreamClosed
	(*Traffic)(nil),       // 10: wiretap.v1.Traffic
	(*Tag)(nil),           // 11: wiretap.v1.Tag
	(*Handshake)(nil),     // 12: wiretap.v1.Handshake
	(*ServerMessage)(nil), // 13: wiretap.v1.ServerMessage
	(*SlowWarning)(nil),   // 14: wiretap.v1.SlowWarning
}
var file_pb_wiretap_proto_depIdxs = []int32{
	2,  // 0: wiretap.v1.TraceEvent.snapshot:type_name -> wiretap.v1.Snapshot
	3,  // 1: wiretap.v1.TraceEvent.string_def:type_name -> wiretap.v1.StringDef
	5,  // 2: wiretap.v1.TraceEvent.conn_opened:type_name -> wiretap.v1.ConnOpened
	6,  // 3: wiretap.v1.TraceEvent.conn_closed:type_name -> wiretap.v1.ConnClosed
	8,  // 4: wiretap.v1.TraceEvent.stream_opened:type_name -> wiretap.v1.StreamOpened
	9,  // 5: wiretap.v1.TraceEvent.stream_closed:type_name -> wiretap.v1.StreamClosed
	10, // 6: wiretap.v1.TraceEvent.traffic:type_name -> wiretap.v1.Traffic
	4,  // 7: wiretap.v1.Snapshot.connections:type_name -> wiretap.v1.ConnInfo
	7,  // 8: wiretap.v1.Snapshot.streams:type_name -> wiretap.v1.StreamInfo
	0,  // 9: wiretap.v1.ConnInfo.direction:type_name -> wiretap.v1.Direction
	4,  // 10: wiretap.v1.ConnOpened.info:type_name -> wiretap.v1.ConnInfo
	0,  // 11: wiretap.v1.StreamInfo.direction:type_name -> wiretap.v1.Direction
	7,  // 12: wiretap.v1.StreamOpened.info:type_name -> wiretap.v1.StreamInfo
	0,  // 13: wiretap.v1.Traffic.direction:type_name -> wiretap.v1.Direction
	11, // 14: wiretap.v1.Traffic.tags:type_name -> wiretap.v1.Tag
	1,  // 15: wiretap.v1.ServerMessage.event:type_name -> wiretap.v1.TraceEvent
	14, // 16: wiretap.v1.ServerMessage.slow:type_name -> wiretap.v1.SlowWarning
	12, // 17: wiretap.v1.WiretapService.StreamEvents:input_type -> wiretap.v1.Handshake
	13, // 18: wiretap.v1.WiretapService.StreamEvents:output_type -> wiretap.v1.ServerMessage
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_pb_wiretap_proto_init() }
func file_pb_wiretap_proto_init() {
	if File_pb_wiretap_proto != nil {
		return
	}
	file_pb_wiretap_proto_msgTypes[0].OneofWrappers = []any{
		(*TraceEvent_Snapshot)(nil),
		(*TraceEvent_StringDef)(nil),
		(*TraceEvent_ConnOpened)(nil),
		(*TraceEvent_ConnClosed)(nil),
		(*TraceEvent_StreamOpened)(nil),
		(*TraceEvent_StreamClosed)(nil),
		(*TraceEvent_Traffic)(nil),
	}
	file_pb_wiretap_proto_msgTypes[12].OneofWrappers = []any{
		(*ServerMessage_Event)(nil),
		(*ServerMessage_Slow)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_wiretap_proto_rawDesc), len(file_pb_wiretap_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_wiretap_proto_goTypes,
		DependencyIndexes: file_pb_wiretap_proto_depIdxs,
		EnumInfos:         file_pb_wiretap_proto_enumTypes,
		MessageInfos:      file_pb_wiretap_proto_msgTypes,
	}.Build()
	File_pb_wiretap_proto = out.File
	file_pb_wiretap_proto_goTypes = nil
	file_pb_wiretap_proto_depIdxs = nil
}
